# Azure Pipelines workflow for CI quality gates
# Runs on push to main/master: restore, build, and all C# tests
# Azure deployment is a separate CD concern and not part of push-based CI

trigger:
  - main
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseDotNet@2
    displayName: Setup .NET
    inputs:
      packageType: 'sdk'
      version: '8.0.x'

  - task: DotNetCoreCLI@2
    displayName: Restore dependencies
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--no-restore'

  - task: DotNetCoreCLI@2
    displayName: Run C# Tests
    inputs:
      command: 'test'
      projects: 'tests/Todo.Api.Tests/Todo.Api.Tests.csproj'
      arguments: '--no-build --verbosity normal'
