using SimpleTodo.Api.Models;

namespace SimpleTodo.Api.Services;

/// <summary>
/// Interface for Story Root service operations, providing business logic
/// for proposal generation, version management, and artifact retrieval.
/// </summary>
public interface IStoryRootService
{
    /// <summary>
    /// Retrieves the current version of the Story Root for the authenticated user.
    /// </summary>
    /// <returns>The current Story Root, or null if no version exists</returns>
    Task<Models.StoryRoot?> GetCurrentStoryRootAsync();

    /// <summary>
    /// Retrieves a specific version of the Story Root by version ID.
    /// </summary>
    /// <param name="versionId">The version identifier</param>
    /// <returns>The Story Root for the specified version, or null if not found</returns>
    Task<Models.StoryRoot?> GetStoryRootVersionAsync(string versionId);

    /// <summary>
    /// Lists all versions of the Story Root for the authenticated user.
    /// </summary>
    /// <returns>List of version metadata, ordered by timestamp (newest first)</returns>
    Task<List<VersionMetadata>> ListStoryRootVersionsAsync();

    /// <summary>
    /// Generates an LLM proposal for merging raw input into the Story Root.
    /// This method does not persist the result - it only generates a proposal.
    /// </summary>
    /// <param name="rawInput">The raw user input to merge</param>
    /// <returns>A Story Root proposal generated by the LLM</returns>
    Task<Models.StoryRoot> ProposeStoryRootMergeAsync(string rawInput);

    /// <summary>
    /// Commits a Story Root proposal as a new version with provenance metadata.
    /// </summary>
    /// <param name="proposal">The Story Root proposal to commit</param>
    /// <param name="identity">Optional identity information for provenance</param>
    /// <returns>The version ID of the newly created version</returns>
    Task<string> CommitStoryRootVersionAsync(Models.StoryRoot proposal, string? identity = null);
}
