using SimpleTodo.Api.Models;

namespace SimpleTodo.Api.Services;

/// <summary>
/// Interface for World State service operations, providing business logic
/// for proposal generation, version management, and artifact retrieval.
/// </summary>
public interface IWorldStateService
{
    /// <summary>
    /// Retrieves the current version of the World State for the authenticated user.
    /// </summary>
    /// <returns>The current World State, or null if no version exists</returns>
    Task<WorldState?> GetCurrentWorldStateAsync();

    /// <summary>
    /// Retrieves a specific version of the World State by version ID.
    /// </summary>
    /// <param name="versionId">The version identifier</param>
    /// <returns>The World State for the specified version, or null if not found</returns>
    Task<WorldState?> GetWorldStateVersionAsync(string versionId);

    /// <summary>
    /// Lists all versions of the World State for the authenticated user.
    /// </summary>
    /// <returns>List of version metadata, ordered by timestamp (newest first)</returns>
    Task<List<VersionMetadata>> ListWorldStateVersionsAsync();

    /// <summary>
    /// Generates an LLM proposal for merging raw input into the World State.
    /// This method does not persist the result - it only generates a proposal.
    /// </summary>
    /// <param name="rawInput">The raw user input to merge</param>
    /// <returns>A World State proposal generated by the LLM</returns>
    Task<WorldState> ProposeWorldStateMergeAsync(string rawInput);

    /// <summary>
    /// Commits a World State proposal as a new version with provenance metadata.
    /// </summary>
    /// <param name="proposal">The World State proposal to commit</param>
    /// <param name="identity">Optional identity information for provenance</param>
    /// <returns>The version ID of the newly created version</returns>
    Task<string> CommitWorldStateVersionAsync(WorldState proposal, string? identity = null);
}
